#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/fruit_shop_dev
#    username: fruit_shop_dev_user
#    password: cadebe
#    platform: mysql
#    driver-class-name: com.mysql.jdbc.Driver
#
#    # Keep the connection alive if idle for a long time (needed in production)
#    dbcp2:
#      test-while-idle: true
#      validation-query: SELECT 1
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database: mysql
#    show-sql: true
##    properties:
##      javax:
##        persistence:
##          schema-generation:
##            create-source: metadata
##            scripts:
##              action: create
##              create-target: database_create.sql